plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"

branches:
  - name: main
  - name: v2
  - name: next
    prerelease: 'beta'
    channel: beta