name: aws-sdk-update-mocks

on:
  push:
    branches:
      - 'renovate/aws-sdk-go-monorepo'

permissions:
  contents: write
  pull-requests: read

jobs:
  go-generate:
    name: go-generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: generate-token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
          revoke: true
      - name: download go mods
        run: |
          go mod download
      - name: go-generate
        run: |
          go generate ./...
      - name: git-commit
        run: |
          git config --global user.name 'ekristen-dev[bot]'
          git config --global user.email '50484080+ekristen-dev[bot]@users.noreply.github.com'
          git add .
          git commit -a -m 'chore: update mocks'
      - name: git-push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          branch: ${{ github.ref }}