name: aws-sdk-update-mocks

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - renovate/aws-sdk-go-monorepo

permissions:
  contents: write
  pull-requests: read

jobs:
  go-generate:
    name: go-generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: download go mods
        run: |
          go mod download
      - run: |
          go generate ./...
      - run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git add .
          git commit -a -m 'chore: update mocks'
          git push
