name: semantic-lint

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  contents: read
  pull-requests: read

jobs:
  semantic-lint:
    if: github.repository == 'ekristen/aws-nuke'
    runs-on: ubuntu-latest
    steps:
      - name: Print debug information
        run: echo "Repository: ${{ github.repository }}"
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
